version: '3.8'

services:
  backend:
    build: .
    container_name: chat_backend
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - .:/app
    environment:
      - NODE_ENV=production
